/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database_test;

import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;
import static oracle.net.aso.b.i;
/**
 *
 * @author planet
 */
public class NewJFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jComboBox1.setSelectedItem(null);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("log in");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database_test/round-account-button-with-user-inside_icon-icons.com_72596.png"))); // NOI18N

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database_test/emblemreadonly_93480.png"))); // NOI18N

        jButton2.setText("log in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrator", "receptionist", "doctor", "analyst", "photographer" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*choose your rule");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(166, 166, 166))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addGap(95, 95, 95))
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{ Class.forName("oracle.jdbc.OracleDriver");
        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE ","idm","123");
         PreparedStatement per = null;
        String x = null;// x to concat the user name with password for comparing with concatination with jtext one and two 
        boolean b=false;// to see if the input user name and password match in database 
        
        //FIND THE USER NAME AND PASSWORD FOR adminstrator
       
        if(jComboBox1.getSelectedItem().toString().equals("administrator")){
               System.out.println("admin");
         per=con.prepareStatement("select user_adm,pass_adm from administrator");
        ResultSet res=per.executeQuery();
        //String x = null;// x to concat the user name with password for comparing with concatination with jtext one and two 
        //boolean b=false;// to see if the input user name and password match in database 
        
        while(res.next()){
            
            x=res.getString(1).concat(res.getString(2));
              System.out.println(x);
            if((jTextField1.getText().concat(jTextField2.getText())).equals(x))
                    {
                        b=true;
                    }
            
           }
       if (b==false)
       JOptionPane.showMessageDialog(this, "there is wrong in user name or password ","error", WIDTH);
       if (b==true)
       {
           per=con.prepareStatement("select fname_adm,lname_adm from administrator where user_adm=(?)");
           per.setString(1, jTextField1.getText());
           res=per.executeQuery();
           
           while(res.next())
           {
            x=res.getString(1).concat(" ").concat(res.getString(2));
             
           }
               
           administrator_interface ai=new administrator_interface(x);
                        ai.setVisible(true); 
                        
       }
        }
       //FIND USER NAME AND PASSWORD FOR RECEPTINIST
        else if (jComboBox1.getSelectedItem().toString().equals("receptionist")){
            System.out.println("rec");
       per=con.prepareStatement("select user_rec,pass_rec from RECEPTIONIST");
     ResultSet res=per.executeQuery();
     while(res.next())
     {
          x=res.getString(1).concat(res.getString(2));
            if((jTextField1.getText().concat(jTextField2.getText())).equals(x))
                    {
                        b=true;
                    }
            
           
     }
     if (b==false)
       JOptionPane.showMessageDialog(this, "there is wrong in user name or password ","error", WIDTH);
       if (b==true)
       {
           per=con.prepareStatement("select fname_rec,lname_rec from RECEPTIONIST where user_rec=(?)");
           per.setString(1, jTextField1.getText());
           res=per.executeQuery();
           
           while(res.next())
           {
            x=res.getString(1).concat(" ").concat(res.getString(2));   
           }
               
           receptionist_interface ri=new receptionist_interface(x);
                        ri.setVisible(true); 
                       
       }
       }
         else if (jComboBox1.getSelectedItem().toString().equals("doctor")){
            System.out.println("doctor");
       per=con.prepareStatement("select user_doc,pass_doc from doctor");
     ResultSet res=per.executeQuery();
     while(res.next())
     {
          x=res.getString(1).concat(res.getString(2));
            if((jTextField1.getText().concat(jTextField2.getText())).equals(x))
                    {
                        b=true;
                    }
            
           
     }
     if (b==false)
       JOptionPane.showMessageDialog(this, "there is wrong in user name or password ","error", WIDTH);
       if (b==true)
       {
           per=con.prepareStatement("select fname_doc,l_name_doc from doctor where user_doc=(?)");
           per.setString(1, jTextField1.getText());
           res=per.executeQuery();
           
           while(res.next())
           {
            x=res.getString(1).concat(" ").concat(res.getString(2));   
           }
           doctor_interface di=new doctor_interface(jTextField1.getText());
           di.setVisible(true);
               
       }
       } else if (jComboBox1.getSelectedItem().toString().equals("analyst")){
            System.out.println("analyst");
      per=con.prepareStatement("select user_ana,pass_ana from analyst");
     ResultSet res=per.executeQuery();
     while(res.next())
     {
          x=res.getString(1).concat(res.getString(2));
            if((jTextField1.getText().concat(jTextField2.getText())).equals(x))
                    {
                        b=true;
                    }
            
           
     }
     if (b==false)
       JOptionPane.showMessageDialog(this, "there is wrong in user name or password ","error", WIDTH);
       if (b==true)
       {
           per=con.prepareStatement("select fname_ana,lname_ana from analyst where user_ana=(?)");
           per.setString(1, jTextField1.getText());
           res=per.executeQuery();
           
           while(res.next())
           {
            x=res.getString(1).concat(" ").concat(res.getString(2));   
           }
               
          analyst_interface ai=new analyst_interface(jTextField1.getText());
               ai.setVisible(true);
       }
       } else if (jComboBox1.getSelectedItem().toString().equals("photographer")){
            System.out.println("photographer");
       per=con.prepareStatement("select user_pho,pass_pho from photographer");
     ResultSet res=per.executeQuery();
     while(res.next())
     {
          x=res.getString(1).concat(res.getString(2));
            if((jTextField1.getText().concat(jTextField2.getText())).equals(x))
                    {
                        b=true;
                    }
            
           
     }
     if (b==false)
       JOptionPane.showMessageDialog(this, "there is wrong in user name or password ","error", WIDTH);
       if (b==true)
       {
           per=con.prepareStatement("select fname_pho,lname_pho from photographer where user_pho=(?)");
           per.setString(1, jTextField1.getText());
           res=per.executeQuery();
           
           while(res.next())
           {
            x=res.getString(1).concat(" ").concat(res.getString(2));   
           }
               
          photographer_interface pi=new photographer_interface(jTextField1.getText());
          pi.setVisible(true);
       }
       }
       per.close();
       con.close();
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
